name: Deploy Bun-based Node.js project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'best-rates'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '20.x'                      # set this to the Node.js version for Bun compatibility

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use 'windows-latest' for Windows
    environment: dev
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Setup Node.js and Bun'
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest' # Specify Bun version if needed
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Bun'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        bun install
        bun build --if-present
        bun test --if-present
        popd

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
